import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import gqlFetch from "../../../utils/gqlFetch";
import PostSansLink from "../../../components/PostSansLink";
import NavBar from "../../../components/NavBar";
import Loading from "../../../components/Loading";
import styles from "../../../styles/Main.module.scss";

const PostPage: NextPage = () => {
	const router = useRouter();
	const { posts, dateFormatted } = gqlFetch();
	const routerId = parseInt(router.query.id! as string);
	if (dateFormatted) {
		return (
			<>
				<div className={styles.mainWrapper}>
					<Head>
					</Head>
					<NavBar />
					<div className={styles.spacer}></div>
					<div className={styles.postContainer}>
						{posts.map((post: any, post_id: number) => {
							if (post.id === routerId) {
								return (
									<>
										<PostSansLink key={post_id} post={post} />
									</>
								);
							}
						})}
					</div>
				</div>
			</>
		);
	} else {
		return (
			<>
				<Head>
					<title>devUserContact_blog</title>
					<meta name="description" content="Generated by create next app" />
					<link rel="icon" href="/favicon.ico" />
				</Head>
				<Loading />
			</>
		);
	}
};
export default PostPage;
